// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtdqpbsavcyfuaikixvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10ZHFwYnNhdmN5ZnVhaWtpeHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNzQ3OTgsImV4cCI6MjA0OTk1MDc5OH0.YIhHhkCk-Hyatt_l3GfGHbRFkoRwq6gJdP99uOGSqyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);